[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_egui = "0.38.1"
dotenvy = "0.15.7"

bevy = { workspace = true }
bevy_spacetimedb = {workspace = true}
spacetimedb-sdk = {workspace = true}
