[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["bevy_dev_tools"] }
bevy_egui = "0.38.1"
dotenvy = "0.15.7"
bevy_spacetimedb = "0.7.2"
spacetimedb-sdk = "1.11.3"
